### ISSUE TITLE
check status of image setting become unchecked in some cases

### ISSUE THREAD

**Issue by grimmerk** [CARTAvis/carta-archived#100]
1st case
1. open more than one files. 
2. open images setting. 
3. Use animator to switch to another file.
4. check status of the image setting become `unchecked`. Bu image setting panel still there.

2nd case:
Similar to 1st case. But `opposite` case. 
1. open more than one files. 
2. open image setting
3. Click statistics window. 
4. Use animator to switch to another file.
5. Still checked. 
6. Uncheck image setting. 
7. Use animator to switch to another file. Now the image setting becomes `checked` status but does not show image setting !!!!!

3rd case. 
1. open any file(s)
2. open image setting.
3. close any file. 
4. check status of the image setting becomes `unchecked`. 

4th case. 
1. open image setting.
2. open new file
3. check status of the image setting becomes `unchecked`.

**Comment by kswang1029** [comment]
I see similar behavior in the "setting" of statistics. Perhaps it is a global issue.
