### ISSUE TITLE
miscellaneous UI improvements

### ISSUE THREAD

**Issue by grimmerk** [CARTAvis/carta-archived#135]
- [x] No more black image and imageSetting shown about 0.x second when launching CARTA.
- [ ] ~Move Data in the left side of the menu.~
- [x] Remove popup?
- [x ] Check hide function
- [x] Auto select image loader when launching CARTA. So the menu will show without clicking the image loader. 
- [x] Modify 'recompute xxx'
- [x] Add some texts next to 95% and region to be some tip of these two functions. 
- [ ] `Close All` menu item.  #95 
- [ ] Remove some items in Preference. 
- [ ] Add Rest Pan & Zoom button. 
- [ ] ~Rename save... to save. ~
- [x] Add more texts to explain whar `Canvas/All images` are.
- [x] update file browser.

**Comment by daikema** [comment]
Can we add "allow files to be opened by double-clicking them" rather than the current approach that requires selecting them and then clicking the load button?

(Wasn't sure if I should open a new issue or add this as a comment here)

**Comment by grimmerk** [comment]
Sounds a good idea. @appolloford & @kswang1029, is it OK to do this?

**Comment by kswang1029** [comment]
unless this improvement will conflict with double-clicking a "folder", it is a good idea.

**Comment by appolloford** [comment]
Done. Maybe you can check the function in the latest PR.
