### ISSUE TITLE
To follow up #40: PC matrix 

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-archived#137]
This issue is related to #40. 

Dirk Petry from ESO has fixed the PC matrix issue when using casa task "exportfits" to generate fits format from casa format. See https://open-jira.nrao.edu/browse/CAS-9993

Now CARTA appears to have a bug that the anti-diagonal elements of the PC matrix are read incorrectly. With the fixed fits image (in our image library: PC_matrix_testImage_with_correctedExportfits), now casaViewer, ds9, and astlib-webDemo do show CONSISTENT gridline plot. **CARTA still shows the rotation differently both in fits AND casa format.** 

carta_debug gives
PC1_1   = 8.660254037844E-01 /                                                  
**PC1_2   = -5.000000000000E-01 /                                                 
PC2_1   = 5.000000000000E-01 /**                                                  
PC2_2   = 8.660254037844E-01 /      

ds9_header gives
PC1_1   =   8.660254037844E-01                                                  
**PC1_2   =   5.000000000000E-01                                                  
PC2_1   =  -5.000000000000E-01**                                                  
PC2_2   =   8.660254037844E-01         

_**Please check carefully how CARTA (casacore+astlib) interprets the PC matrix in header. We better solve this in version 0.9 prerelease**_
![carta_pc_matrix_issue](https://cloud.githubusercontent.com/assets/20819712/25711611/f206ba66-3121-11e7-9229-67a881ebc329.png)

**Comment by kswang1029** [comment]
To update, it is a bug of casacore. Once the relevant commits are there, we can rebuild casacore to solve this issue. So we just have to wait.

**Comment by CNOCycle** [comment]
New version of casacore uses new namespace `casacore`.
Does namespace in CARTA need to be upgrade before we rebuild casacore?

**Comment by grimmerk** [comment]
It seems so.

**Comment by grimmerk** [comment]
Fixed in the latest casa lib.  #188
