### ISSUE TITLE
Performance: use header info DATAMAX DATAMIN (if exists) to skip percentile calculation when loading images

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-archived#148]
If the image header contains DATAMAX and DATAMIN keyword, we could actually skip percentile calculations when loading images into CARTA. This should significantly improve performance for big files. 

Please check the code to see how CARTA handles different image formats and to see if we can skip percentile call if there are DATAMAX and DATAMIN keyword.

Things to check: does CARTA perform percentile calculations when loading images? Since sqlite db is working now (indeed, open a same image for the second time is faster than the first time, I guess if cached DATAMAX and DATAMIN are found in db, percentile call will be skipped. We can actually borrow the same idea but the source of DATAMAX and DATAMIN is actually from the data header itself.

**Comment by grimmer0125** [comment]
Extra items:
1. profiler. 
2. check duplicate calculation 
3. improvement about percentile.

**Comment by grimmerk** [comment]
After discussing, people may try to modify the file header so that this information can not be trusted. So change its status to pending.

**Comment by kswang1029** [comment]
close this issue is okay I think.
