### ISSUE TITLE
Ellipse area is not consistent with the drawn shape of the ellipse

### ISSUE THREAD

**Issue by JamieDass** [CARTAvis/carta-archived#172]
The (clickable) area of an ellipse region does not match the drawn shape of the region.
Instead the clickable area is rotated 90 degrees from the drawn region — i.e. the major and minor radius are inverted.

To reproduce:
Draw an ellipse and try to drag it by clicking inside the region but near the edges along the longest axis.

You can also drag by clicking **outside** the region but near the centre of the ellipse. This should not be possible.

To illustrate please see the attached image. The ellipse with the solid line is what is visible to the user, but the dotted line is the clickable area of the region (and possibly the true geometric area used for region statistics etc! — haven't tested this).

![ellipse broken](https://user-images.githubusercontent.com/20866295/27343020-f1983afe-559e-11e7-93be-c6244adfccf6.png)

**Comment by kswang1029** [comment]
Solved by #207 and merged. Close this issue.
