### ISSUE TITLE
Ellipse region moves to the right before dragging

### ISSUE THREAD

**Issue by JamieDass** [CARTAvis/carta-archived#173]
If a user drags an ellipse region that is bigger in the x direction than in the y direction, the region first jumps to the right before performing the drag action. The jump is the same size as the width of the ellipse (i.e. 2x the major radius).

To reproduce:

1. Draw an ellipse region that is wider than it is high
2. Try to drag the ellipse by clicking in the middle and moving the mouse
3. The region will immediately move to the right and **then** act as if it's being dragged from a new starting point

(Right now I'm not sure if this is related to issue #171 but it's possible)

**Comment by kswang1029** [comment]
fixed in #197
