### ISSUE TITLE
Change the default DB path used by Sqlite cache plugin in the embedded plugin

### ISSUE THREAD

**Issue by grimmerk** [CARTAvis/carta-archived#189]
@ajm-asiaa , could you write your proposal path here?

**Comment by ajm-ska** [comment]
I propose it can be be just put inside the existing ~/CARTA folder (the CARTA folder in the user's home directory)

At the moment, the ~/CARTA directory structure is like this:

~/CARTA  
---------- Images
---------- snapshots >
----------------------- data
----------------------- layout
----------------------- preferences

`Images` contains a copy of the sample images. There is no sense putting in the `snapshots` folder.

Maybe to keep things neat we could put it in a folder called `cache` inside ~/CARTA e.g. 
`~/CARTA > cache > carta_sql_cache`

What do you think?

**Comment by grimmerk** [comment]
@markccchiang , how do you think? By the way, another suggestion from @kswang1029 is, we can automatically make a copy of embedded config.json into ~/.cartavis/, so users do not need to crate this if they want to modify and also users can use this as a reference.

**Comment by ajm-ska** [comment]
The config.json file in the ~/.cartavis/ directory was the original way that we decided to change to simplify things for the user. But we can easily bring it back. 

It would just need a line in setupcartavis.py to copy config.json from $dirname/../etc/config to $HOME/.cartavis.

**Comment by grimmerk** [comment]
try one of the following actions 
1. add a UI item to open this embedded config.json, so no more copy to ~/
or 
2. copy to ~/ (current way)
