### ISSUE TITLE
show "offset" in Axes/Border -> X axis/Y axis for linear type file and channel -> velocity (but the ideal is velocity & frequency)

### ISSUE THREAD

**Issue by grimmerk** [CARTAvis/carta-archived#65]
related to: #70 

Regarding `but the ideal is velocity & frequency`, #164 has implemented the function, velocity <->spectral but #164 will not change/sync with Axes/Border.

**Comment by grimmerk** [comment]
Need implement this issue with 
no4. in https://github.com/CARTAvis/carta/issues/70#issuecomment-298851693 

Show correct velocity or frequency in Axes/Border.

**Comment by grimmerk** [comment]
In this issue, We have correctly shown "velocity" instead of "channel" for PV image. 

Summary:
Previous    Done 
linear     ->   offset
channel  ->  only velocity (but the target is velocity/frequency)

**Comment by kswang1029** [comment]
checked. When opening a pv image, default we will see offset vs radio velocity.
