### ISSUE TITLE
Not able to use histogram/profiler/image layout, jump back to the default statistics layout, fix #56 again.

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-archived#68]
1) launch desktop-linux (built with docker)
2) open noise.miriad (this step is optional, can be skipped. i.e. no need to open an image)
3) set layout to histogram layout (or profiler layout or image layout)
4) click the histogram panel (or profiler panel or imageViewer panel)
5) we should see the layout changed back to default one with statistics. This issue repeats if we go to step 3) and so on.

**Comment by grimmerk** [comment]
This is due to #56 , and I have reverted it several minutes ago. Please try again.

**Comment by kswang1029** [comment]
Oh I see. Then I have to rebuild

**Comment by kswang1029** [comment]
With the latest develop, now this issue is fixed. Thanks.

**Comment by grimmerk** [comment]
due to the side effect of #56, now we reverted, so we need to fix #56 again.
