### ISSUE TITLE
cf:CAS-9860 plotting contours slows down movie significantly

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-archived#74]
Plotting contours slows down movie significantly. 
To feel it, try
1) open "M100_12m_CO_central.image.fits"
2) play movie only for the first loop and pay attention to the speed.
3) enable image settings and set contours: method=range, min=0.05, max=0.3, level_count=7, spacing=linear. Then hit "Add/update contour set" button.
4) play movie again and pay attention to the speed. The speed significantly drops and has impact on UX as plotting contours is an essential function to assist image inspection.

**Comment by grimmerk** [comment]
note: when enabling imageContext or imageZoom, will slow too.

**Comment by grimmerk** [comment]
@chyan26 , two candidates of the replacement of the current contour algorithm:

1. DS9's contour algorithm. https://github.com/SAOImageDS9/SAOImageDS9/blob/d7ff6fa1f451f9c32a6caf80e91c679a17d7e3af/tksao/frame/fvcontour.C and it does not just connect each point and does some optimation. 	

2. casaviewer's contour part which is using pgplot.

**Comment by markccchiang** [comment]
The solver of this issue is referred to #199.
