### ISSUE TITLE
cf:CAS-9813 profiler should show nothing for single channel images

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-archived#76]
Profiler plugin should show the spectrum ONLY for image "cube", not for single channel image. The attached plot demonstrates this issue. The input image is a single channel image with Gaussian noise. Looks like the "spectrum" is the "noise".
<img width="1250" alt="screen shot 2017-03-02 at 5 20 35 pm" src="https://cloud.githubusercontent.com/assets/20819712/25420187/712ab1ca-2a89-11e7-9892-f099dcee0c6d.png">

**Comment by grimmerk** [comment]
fixed.
