### ISSUE TITLE
cf:CAS-9774 histogram not shown completely OR not shown correctly

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-archived#77]
full discussions and attached plots can be found at https://open-jira.nrao.edu/browse/CAS-9774

Here I report a bug spotted from carta-mac-20170125b.
1) Histogram plugin is not always working. For example, aJ.fits works but HLTau_Band7_Continuum.fits doesn't.
2) With controlled input images (images with constant intensity of 1 Jy plus Gaussian noise 0.1 Jy), we should see Gaussian shape in the histogram. Attached image demonstrates the bug here: we only see half of the Gaussian (The correct histogram generated with casaViewer is also attached). Since all pixels are > 0, we should see full Gaussian. Test images can be found at /data/carta_image_library/Images/noise_*px_*px.fits
3) bin count doesn't match what we see in GUI.

**Comment by grimmerk** [comment]
@kswang1029 ,  does it refer to the following items (from your notes):
1. bin count is not consistent with what user expects
2. incorrect x-range

**Comment by kswang1029** [comment]
Yes, we should fix both issues.

**Comment by grimmerk** [comment]
copy from #99 , 

open noise_11px_11_px.fits, no histogram is seen
open noise_10px_10_px.fits, a histogram is seen but the content is not correct.

**Comment by grimmerk** [comment]
fixed.
