### ISSUE TITLE
in some cases, image can not be zoom in

### ISSUE THREAD

**Issue by grimmerk** [CARTAvis/carta-archived#80]
ref: #52
ref: #66
ref: #64 

How to reproduce:

case1:
1. open a file.
2. resize the window and make it bigger. 
3. can not zoom in this image. !! <- Bug.

**Comment by grimmerk** [comment]
@kswang1029 , 

The current situation is, when people permute the axes, CARTA will not automatically let the image fit the window. This is due to this change, https://github.com/CARTAvis/carta/commit/741a532d71062f0c81fd435d2d2ddac76b45a817, which is solving https://github.com/CARTAvis/carta/issues/64. Before it would fit it when permutating. 

If it needs to add it back, please tell me. The possible solution is to compare the different [x,y] in these two times stack info.

**Comment by kswang1029** [comment]
Yes, please. It makes more sense to always fill up the imageViewer after permutation.

**Comment by grimmerk** [comment]
@kswang1029 , 0e21d8370adfb3837d4b08a615243d98fefee32b has made CARTA auto-fit when permutating the image.
