### ISSUE TITLE
now always use j2000 coordinate system as default system, regardless the system in file header

### ISSUE THREAD

**Issue by grimmerk** [CARTAvis/carta-archived#97]

**Comment by low-sky** [comment]
What is the reasoning for this?  I'm thinking that Galactic frame images are best suited to being shown in Galactic coordinates by default.

**Comment by kswang1029** [comment]
Current feature of carta is that regardless the coordinate system defined in header, what users see is always j2000. Coordinate transformation to j2000 will be performed for systems other than j2000. This is not what users expect to see. That's why this issue is opened and we shell fix it.

**Comment by low-sky** [comment]
Ah, understood.  I didn't realize this was a Bug and not a Feature Request.
